# This is a basic workflow to help you get started with Actions

name: After push to staging, merge to testing and devel

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ staging ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  merge:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Merge To Testing
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        uses: MaximeHeckel/github-action-merge-fast-forward@v1.1.0
        with:
          # Branch to merge
          branchtomerge: staging
          # Branch that will be updated
          branch: testing

      - name: Merge To Devel
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        uses: MaximeHeckel/github-action-merge-fast-forward@v1.1.0
        with:
          # Branch to merge
          branchtomerge: testing
          # Branch that will be updated
          branch: devel
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
