name: Main

on:
  push:
    branches: [ staging ]


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
      - name: git-bash
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        uses: fnkr/github-action-git-bash@v1.1
        with:
          args: 'bash -c "git fetch && git checkout staging && git pull origin staging && git checkout testing && git pull origin testing && git pull origin --allow-unrelated-histories staging && git push origin testing"'
